import { Router } from 'express';
import auth from './auth.js';
import users from './users.js';
import tasks from './tasks.js';
import notes from './notes.js';
import exams from './exams.js';
import studyPlans from './studyPlans.js';
import focus from './focus.js';
import productivity from './productivity.js';
import wellness from './wellness.js';
import career from './career.js';
import lifeSkills from './lifeSkills.js';
import ai from './ai.js';
import social from './social.js';
import marketplace from './marketplace.js';
import notifications from './notifications.js';
import dashboard from './dashboard.js';
import admin from './admin.js';

const r = Router();
r.use('/auth', auth);
r.use('/users', users);
r.use('/tasks', tasks);
r.use('/notes', notes);
r.use('/exams', exams);
r.use('/study-plans', studyPlans);
r.use('/focus', focus);
r.use('/productivity', productivity);
r.use('/wellness', wellness);
r.use('/career', career);
r.use('/life-skills', lifeSkills);
r.use('/ai', ai);
r.use('/social', social);
r.use('/marketplace', marketplace);
r.use('/notifications', notifications);
r.use('/dashboard', dashboard);
r.use('/admin', admin);

export default r;
